import type { Metadata } from 'next';
import { Geist, Geist_Mono, Mona_Sans } from 'next/font/google';
import './globals.css';
import '../lib/orpc.server';
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { extractRouterConfig } from 'uploadthing/server';
import { Toaster } from '@/components/ui/sonner';
import { TanstackQueryClientProvider } from '@/providers/query-client-provider';
import { ourFileRouter } from './api/uploadthing/core';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const monaSans = Mona_Sans({
  variable: '--font-mona-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${monaSans.variable} antialiased`}
      >
        <NuqsAdapter>
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <TanstackQueryClientProvider>
            {children}
            <Toaster position="top-center" />
          </TanstackQueryClientProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
